<?php

namespace App\Domains\Analytics\Controllers;

use App\Domains\Evacuations\Models\EvacuationRecord;
use App\Domains\EvacuationCenters\Models\EvacuationCenter;
use App\Domains\Evacuations\Models\EvacuatedMember;
use App\Domains\EvacuationEvents\Models\DisasterEvent;
use App\Domains\ResourceRequests\Models\ResourceRequest;
use App\Domains\CenterIssueReports\Models\CenterIssueReport;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use OpenApi\Attributes as OA;
use App\Http\Controllers\API\BaseApiController;

class AnalyticsExportController extends BaseApiController
{
    // ─── SHARED FILTER HELPERS ───



    private function applyFilters(Request $request, $query, $centerField = 'center_id', $dateField = 'created_at')
    {
        $user = Auth::user();

        if ($request->filled('event_id') && $request->event_id !== 'all') {
            $query->where('event_id', $request->event_id);
        }

        if ($user->isEvacPersonnel() && $user->assigned_center_id) {
            $query->where($centerField, $user->assigned_center_id);
        } elseif ($request->filled('center_id') && $request->center_id !== 'all') {
            $query->where($centerField, $request->center_id);
        }

        if ($request->filled('start_date')) {
            $query->whereDate($dateField, '>=', $request->start_date);
        }
        if ($request->filled('end_date')) {
            $query->whereDate($dateField, '<=', $request->end_date);
        }

        return $query;
    }

    private function getFilterMeta(Request $request): array
    {
        $eventName = 'All Events';
        if ($request->filled('event_id') && $request->event_id !== 'all') {
            $event = DisasterEvent::find($request->event_id);
            $eventName = $event?->name ?? $request->event_id;
        }

        $centerName = 'All Centers';
        $user = Auth::user();
        if ($user->isEvacPersonnel() && $user->assigned_center_id) {
            $center = EvacuationCenter::find($user->assigned_center_id);
            $centerName = $center?->name ?? 'Assigned Center';
        } elseif ($request->filled('center_id') && $request->center_id !== 'all') {
            $center = EvacuationCenter::find($request->center_id);
            $centerName = $center?->name ?? $request->center_id;
        }

        return [
            'event' => $eventName,
            'center' => $centerName,
            'start_date' => $request->input('start_date', 'N/A'),
            'end_date' => $request->input('end_date', 'N/A'),
            'generated_at' => now()->format('Y-m-d H:i:s'),
            'generated_by' => Auth::user()?->name ?? '',
        ];
    }

    private function respond(Request $request, array $headers, array $rows, string $filePrefix, string $pdfView, array $pdfData, array $totalsRows = [])
    {
        $format = $request->input('format', 'csv');

        if ($format === 'pdf') {
            $pdf = Pdf::loadView($pdfView, $pdfData)
                ->setPaper('a4', 'landscape')
                ->setOption('isRemoteEnabled', true);

            $fileName = $filePrefix . '_' . now()->format('Y-m-d') . '.pdf';
            return $pdf->download($fileName);
        }

        $meta = $pdfData['meta'] ?? [];
        if (!empty($meta)) {
            $meta['title'] = $pdfData['title'] ?? $filePrefix;
        }

        $fileName = $filePrefix . '_' . now()->format('Y-m-d') . '.csv';
        return $this->streamCsv($fileName, $headers, $rows, $meta, $totalsRows);
    }

    private function streamCsv(string $fileName, array $headers, array $rows, array $meta = [], array $totalsRows = []): StreamedResponse
    {
        return new StreamedResponse(function () use ($headers, $rows, $meta, $totalsRows) {
            $handle = fopen('php://output', 'w');
            fprintf($handle, chr(0xEF) . chr(0xBB) . chr(0xBF));

            // ── Meta block (self-describing header for Excel/Sheets) ──
            if (!empty($meta)) {
                fputcsv($handle, ['EvaTrack Emergency Response Platform — Analytics Export']);
                fputcsv($handle, []);
                fputcsv($handle, ['Report',            $meta['title'] ?? '']);
                fputcsv($handle, ['Disaster Event',     $meta['event'] ?? 'All Events']);
                fputcsv($handle, ['Evacuation Center',  $meta['center'] ?? 'All Centers']);
                fputcsv($handle, ['Date Range',
                    ($meta['start_date'] !== 'N/A' || $meta['end_date'] !== 'N/A')
                        ? ($meta['start_date'] . ' to ' . $meta['end_date'])
                        : 'All Dates'
                ]);
                fputcsv($handle, ['Generated By',      $meta['generated_by'] ?? '']);
                fputcsv($handle, ['Generated At',      $meta['generated_at'] ?? '']);
                fputcsv($handle, []);
                fputcsv($handle, ['NOTE: For official DRRM use only. Do not redistribute without authorization.']);
                fputcsv($handle, []);
                fputcsv($handle, ['--- DATA STARTS BELOW ---']);
                fputcsv($handle, []);
            }

            // ── Column headers + data rows ──
            fputcsv($handle, $headers);
            foreach ($rows as $row) {
                fputcsv($handle, $row);
            }

            // ── Totals / summary block ──
            if (!empty($totalsRows)) {
                fputcsv($handle, []);
                fputcsv($handle, ['--- SUMMARY TOTALS ---']);
                foreach ($totalsRows as $tr) {
                    fputcsv($handle, $tr);
                }
            }

            fputcsv($handle, []);
            fputcsv($handle, ['Generated by EvaTrack Emergency Response Platform — ' . now()->format('F j, Y H:i')]);

            fclose($handle);
        }, 200, [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
            'Cache-Control' => 'no-cache, no-store, must-revalidate',
        ]);
    }

    private function sanitize(string $name): string
    {
        return preg_replace('/[^A-Za-z0-9_\-]/', '_', str_replace(' ', '_', $name));
    }

    private function getAgeGroup(?int $age): string
    {
        if ($age === null) return '';
        if ($age <= 12) return 'Children (0-12)';
        if ($age <= 17) return 'Youth (13-17)';
        if ($age <= 59) return 'Adults (18-59)';
        return 'Senior (60+)';
    }

    private function getGenderKey($m): string
    {
        $relation = $m->getRelation('gender');
        if ($relation instanceof \App\Domains\ReferenceData\Models\Gender) {
            return $relation->gender_key;
        }

        $genderVal = $m->gender;
        if ($genderVal instanceof \App\Domains\ReferenceData\Models\Gender) {
            return $genderVal->gender_key;
        }

        if (is_string($genderVal)) {
            return strtolower($genderVal);
        }

        return '';
    }

    private function getGenderLabel($m): string
    {
        $relation = $m->getRelation('gender');
        if ($relation instanceof \App\Domains\ReferenceData\Models\Gender) {
            return $relation->gender_label;
        }

        $genderVal = $m->gender;
        if ($genderVal instanceof \App\Domains\ReferenceData\Models\Gender) {
            return $genderVal->gender_label;
        }

        if (is_string($genderVal)) {
            return ucfirst($genderVal);
        }

        return '';
    }

    // ─── 1. DROMIC MASTER LIST ───

    #[OA\Get(
        path: '/analytics/export/dromic',
        summary: 'Export DROMIC Master List',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'event_id', in: 'query', description: 'Filter by event ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'format', in: 'query', description: 'Export format (csv, pdf)', required: false, schema: new OA\Schema(type: 'string', enum: ['csv', 'pdf'], default: 'csv'))]
    #[OA\Response(response: 200, description: 'Success')]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function dromicMasterList(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');
        $meta = $this->getFilterMeta($request);

        $query = EvacuationRecord::with([
            'household.address.barangay.city.province',
            'household.address.purok', 'household.address.sitio',
            'household.members.gender',
            'household.members.vulnerableGroupDetails',
            'evacuatedMembers.member',
            'unitAllocations.unit.type',
            'event', 'verifier', 'center',
        ])->where('household_status_id', 2);

        $this->applyFilters($request, $query);
        $records = $query->latest('verified_at')->get();

        $headers = [
            'No.','Disaster Event','Evacuation Center','Household ID','Family Name',
            'Contact Number','Home Address','Total Members','Male','Female',
            'Children (0-12)','Youth (13-17)','Adults (18-59)','Senior (60+)',
            'PWD','Pregnant','Indigenous','Allocated Unit','Date Admitted','Admitted By',
        ];

        $rows = [];
        $no = 1;
        foreach ($records as $record) {
            $hh = $record->household;
            $evacuatedMemberIds = $record->evacuatedMembers->pluck('member_id')->toArray();
            $members = $hh?->members?->filter(fn($m) => in_array($m->member_id, $evacuatedMemberIds)) ?? collect();

            $male = $female = $children = $youth = $adults = $elderly = $pwd = $pregnant = $indigenous = 0;
            foreach ($members as $m) {
                $gk = $this->getGenderKey($m);
                if ($gk === 'male') $male++;
                elseif ($gk === 'female') $female++;
                $age = $m->birth_date ? Carbon::parse($m->birth_date)->age : null;
                if ($age !== null) {
                    if ($age <= 12) $children++;
                    elseif ($age <= 17) $youth++;
                    elseif ($age <= 59) $adults++;
                    else $elderly++;
                }
                $vgKeys = $m->vulnerableGroupDetails->pluck('vulnerable_group_key')->toArray();
                if (in_array('pwd', $vgKeys)) $pwd++;
                if (in_array('pregnant', $vgKeys)) $pregnant++;
                if (in_array('indigenous', $vgKeys)) $indigenous++;
            }

            $unit = $record->unitAllocations->first();
            $rows[] = [
                $no++,
                $record->event?->name ?? '',
                $record->center?->name ?? '',
                $record->household_id,
                $hh?->household_name ?? '',
                $hh?->contact_number ?? '',
                $hh?->address ? $hh->address->full_address : '',
                $record->evacuated_count ?? 0,
                $male, $female, $children, $youth, $adults, $elderly,
                $pwd, $pregnant, $indigenous,
                $unit?->unit?->name ?? 'Unassigned',
                $record->verified_at ? Carbon::parse($record->verified_at)->format('Y-m-d H:i') : '',
                $record->verifier?->name ?? '',
            ];
        }

        $totalsRows = [
            ['Total Families',          count($rows)],
            ['Total Individuals',        array_sum(array_column($rows, 7))],
            ['Male',                     array_sum(array_column($rows, 8))],
            ['Female',                   array_sum(array_column($rows, 9))],
            ['Children (0-12)',          array_sum(array_column($rows, 10))],
            ['Youth (13-17)',            array_sum(array_column($rows, 11))],
            ['Adults (18-59)',           array_sum(array_column($rows, 12))],
            ['Senior Citizens (60+)',    array_sum(array_column($rows, 13))],
            ['PWD',                      array_sum(array_column($rows, 14))],
            ['Pregnant',                 array_sum(array_column($rows, 15))],
            ['Indigenous People',        array_sum(array_column($rows, 16))],
        ];

        return $this->respond($request, $headers, $rows, 'DROMIC_MasterList', 'exports.dromic', [
            'meta' => $meta, 'headers' => $headers, 'rows' => $rows, 'title' => 'DROMIC Master List of Evacuees',
        ], $totalsRows);
    }

    // ─── 2. DEMOGRAPHIC SUMMARY ───

    #[OA\Get(
        path: '/analytics/export/demographics',
        summary: 'Export Demographic Summary',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'event_id', in: 'query', description: 'Filter by event ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'format', in: 'query', description: 'Export format (csv, pdf)', required: false, schema: new OA\Schema(type: 'string', enum: ['csv', 'pdf'], default: 'csv'))]
    #[OA\Response(response: 200, description: 'Success')]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function demographicSummary(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');
        $meta = $this->getFilterMeta($request);

        $query = EvacuationRecord::where('household_status_id', 2);
        $this->applyFilters($request, $query);
        $evacuationIds = $query->pluck('evacuation_id');

        $members = EvacuatedMember::with(['member.gender', 'member.vulnerableGroupDetails'])
            ->whereIn('evacuation_id', $evacuationIds)->get();

        $totalHouseholds = $query->distinct('household_id')->count('household_id');
        $totalIndividuals = $members->count();
        $male = $female = $children = $youth = $adults = $elderly = 0;
        $vulnCounts = [];

        foreach ($members as $em) {
            $m = $em->member;
            if (!$m) continue;
            $gk = $this->getGenderKey($m);
            if ($gk === 'male') $male++;
            elseif ($gk === 'female') $female++;
            $age = $m->birth_date ? Carbon::parse($m->birth_date)->age : null;
            if ($age !== null) {
                if ($age <= 12) $children++;
                elseif ($age <= 17) $youth++;
                elseif ($age <= 59) $adults++;
                else $elderly++;
            }
            foreach ($m->vulnerableGroupDetails as $vg) {
                $vulnCounts[$vg->vulnerable_group_label] = ($vulnCounts[$vg->vulnerable_group_label] ?? 0) + 1;
            }
        }

        $headers = ['Metric', 'Count', 'Percentage'];
        $rows = [
            ['POPULATION SUMMARY', '', ''],
            ['Total Households', $totalHouseholds, ''],
            ['Total Individuals', $totalIndividuals, '100%'],
            ['', '', ''],
            ['GENDER BREAKDOWN', '', ''],
            ['Male', $male, $totalIndividuals > 0 ? round(($male / $totalIndividuals) * 100, 1) . '%' : '0%'],
            ['Female', $female, $totalIndividuals > 0 ? round(($female / $totalIndividuals) * 100, 1) . '%' : '0%'],
            ['', '', ''],
            ['AGE DISTRIBUTION', '', ''],
            ['Children (0-12)', $children, $totalIndividuals > 0 ? round(($children / $totalIndividuals) * 100, 1) . '%' : '0%'],
            ['Youth (13-17)', $youth, $totalIndividuals > 0 ? round(($youth / $totalIndividuals) * 100, 1) . '%' : '0%'],
            ['Adults (18-59)', $adults, $totalIndividuals > 0 ? round(($adults / $totalIndividuals) * 100, 1) . '%' : '0%'],
            ['Senior Citizens (60+)', $elderly, $totalIndividuals > 0 ? round(($elderly / $totalIndividuals) * 100, 1) . '%' : '0%'],
            ['', '', ''],
            ['VULNERABLE GROUPS', '', ''],
        ];
        foreach ($vulnCounts as $label => $count) {
            $rows[] = [$label, $count, $totalIndividuals > 0 ? round(($count / $totalIndividuals) * 100, 1) . '%' : '0%'];
        }

        $pdfData = compact('meta', 'totalHouseholds', 'totalIndividuals', 'male', 'female', 'children', 'youth', 'adults', 'elderly', 'vulnCounts');
        $pdfData['title'] = 'Demographic Summary Report';

        return $this->respond($request, $headers, $rows, 'Demographic_Summary', 'exports.demographic', $pdfData);
    }

    // ─── 3. CENTER UTILIZATION ───

    #[OA\Get(
        path: '/analytics/export/utilization',
        summary: 'Export Center Utilization Summary',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'event_id', in: 'query', description: 'Filter by event ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'format', in: 'query', description: 'Export format (csv, pdf)', required: false, schema: new OA\Schema(type: 'string', enum: ['csv', 'pdf'], default: 'csv'))]
    #[OA\Response(response: 200, description: 'Success')]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function centerUtilization(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');
        $meta = $this->getFilterMeta($request);

        $query = EvacuationRecord::where('household_status_id', 2);
        $this->applyFilters($request, $query);

        $records = $query->get();
        $centerIds = $records->pluck('center_id')->unique();
        $centers = EvacuationCenter::with('accommodationUnits.unitAllocations')
            ->whereIn('evacuation_center_id', $centerIds)->get();

        $headers = [
            'Evacuation Center','Address','Total Capacity','Current Occupants','Available Slots',
            'Utilization %','Total Households','Total Units','Occupied Units','Available Units','Status',
        ];

        $rows = [];
        foreach ($centers as $center) {
            $centerRecords = $records->where('center_id', $center->evacuation_center_id);
            $occupants = (int) $centerRecords->sum('evacuated_count');
            $households = $centerRecords->pluck('household_id')->unique()->count();
            $capacity = (int) $center->capacity;
            $available = max(0, $capacity - $occupants);
            $pct = $capacity > 0 ? round(($occupants / $capacity) * 100, 1) : 0;
            $totalUnits = $center->accommodationUnits->count();
            $occupiedUnits = $center->accommodationUnits->filter(fn($u) => $u->unitAllocations->count() > 0)->count();

            $rows[] = [
                $center->name, $center->osm_address, $capacity, $occupants, $available,
                $pct . '%', $households, $totalUnits, $occupiedUnits, $totalUnits - $occupiedUnits,
                $pct >= 90 ? 'Overcapacity' : ($pct >= 70 ? 'Near Capacity' : 'Optimal'),
            ];
        }

        $totalsRows = [
            ['Total Centers',       count($rows)],
            ['Total Capacity',      array_sum(array_column($rows, 2))],
            ['Total Occupants',     array_sum(array_column($rows, 3))],
            ['Available Slots',     array_sum(array_column($rows, 4))],
            ['Total Households',    array_sum(array_column($rows, 6))],
            ['Total Units',         array_sum(array_column($rows, 7))],
            ['Occupied Units',      array_sum(array_column($rows, 8))],
        ];

        return $this->respond($request, $headers, $rows, 'Center_Utilization', 'exports.center-utilization', [
            'meta' => $meta, 'headers' => $headers, 'rows' => $rows, 'title' => 'Center Utilization & Capacity Report',
        ], $totalsRows);
    }

    // ─── 4. VULNERABLE GROUPS CARE LIST ───

    #[OA\Get(
        path: '/analytics/export/vulnerable',
        summary: 'Export Vulnerable Groups Care List',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'event_id', in: 'query', description: 'Filter by event ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'format', in: 'query', description: 'Export format (csv, pdf)', required: false, schema: new OA\Schema(type: 'string', enum: ['csv', 'pdf'], default: 'csv'))]
    #[OA\Response(response: 200, description: 'Success')]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function vulnerableGroups(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');
        $meta = $this->getFilterMeta($request);

        $query = EvacuationRecord::with([
            'household.address.barangay.city.province',
            'household.members.gender', 'household.members.vulnerableGroupDetails',
            'evacuatedMembers', 'unitAllocations.unit', 'center',
        ])->where('household_status_id', 2);
        $this->applyFilters($request, $query);
        $records = $query->get();

        $headers = [
            'Evacuation Center','Household Name','Member Name','Age','Gender',
            'Vulnerability Type','Contact Number','Allocated Unit','Home Address',
        ];

        $rows = [];
        foreach ($records as $record) {
            $hh = $record->household;
            $evacuatedIds = $record->evacuatedMembers->pluck('member_id')->toArray();
            $unit = $record->unitAllocations->first();

            foreach ($hh?->members ?? [] as $m) {
                if (!in_array($m->member_id, $evacuatedIds)) continue;
                $vgLabels = $m->vulnerableGroupDetails->pluck('vulnerable_group_label')->toArray();
                if (empty($vgLabels)) continue;

                $age = $m->birth_date ? Carbon::parse($m->birth_date)->age : null;
                if ($age !== null && $age >= 60 && !in_array('Elderly', $vgLabels)) {
                    $vgLabels[] = 'Elderly';
                }

                $rows[] = [
                    $record->center?->name ?? '',
                    $hh->household_name ?? '',
                    trim(($m->first_name ?? '') . ' ' . ($m->middle_name ?? '') . ' ' . ($m->last_name ?? '')),
                    $age ?? '', $this->getGenderLabel($m),
                    implode(', ', $vgLabels),
                    $hh->contact_number ?? '',
                    $unit?->unit?->name ?? 'Unassigned',
                    $hh->address ? $hh->address->full_address : '',
                ];
            }
        }

        $totalsRows = [
            ['Total Vulnerable Individuals', count($rows)],
        ];

        return $this->respond($request, $headers, $rows, 'Vulnerable_Groups', 'exports.vulnerable-groups', [
            'meta' => $meta, 'headers' => $headers, 'rows' => $rows, 'title' => 'Vulnerable Groups Care List',
        ], $totalsRows);
    }

    // ─── 5. RESOURCE REQUESTS ───

    #[OA\Get(
        path: '/analytics/export/resources',
        summary: 'Export Resource Requests Summary',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'format', in: 'query', description: 'Export format (csv, pdf)', required: false, schema: new OA\Schema(type: 'string', enum: ['csv', 'pdf'], default: 'csv'))]
    #[OA\Response(response: 200, description: 'Success')]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function resourceRequests(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');
        $meta = $this->getFilterMeta($request);

        $query = ResourceRequest::with(['center', 'requester', 'handler', 'urgencyLevel', 'status']);

        $user = Auth::user();
        if ($user->isEvacPersonnel() && $user->assigned_center_id) {
            $query->where('evacuation_center_id', $user->assigned_center_id);
        } elseif ($request->filled('center_id') && $request->center_id !== 'all') {
            $query->where('evacuation_center_id', $request->center_id);
        }
        if ($request->filled('start_date')) $query->whereDate('created_at', '>=', $request->start_date);
        if ($request->filled('end_date')) $query->whereDate('created_at', '<=', $request->end_date);

        $items = $query->latest()->get();

        $headers = [
            'Request ID','Evacuation Center','Resource Type','Quantity','Description',
            'Urgency','Status','Requested By','Handled By','Date Requested','Date Updated',
        ];

        $rows = [];
        foreach ($items as $item) {
            $rows[] = [
                $item->request_id,
                $item->center?->name ?? '',
                $item->resource_type ?? '',
                $item->quantity ?? '',
                $item->description ?? '',
                $item->urgencyLevel?->urgency_label ?? '',
                $item->status?->status_label ?? '',
                $item->requester?->name ?? '',
                $item->handler?->name ?? '',
                $item->created_at?->format('Y-m-d H:i') ?? '',
                $item->updated_at?->format('Y-m-d H:i') ?? '',
            ];
        }

        $totalsRows = [
            ['Total Requests',   count($rows)],
            ['Pending',          count(array_filter($rows, fn($r) => stripos($r[6] ?? '', 'pending') !== false))],
            ['Fulfilled',        count(array_filter($rows, fn($r) => stripos($r[6] ?? '', 'fulfilled') !== false))],
        ];

        return $this->respond($request, $headers, $rows, 'Resource_Requests', 'exports.table-report', [
            'meta' => $meta, 'headers' => $headers, 'rows' => $rows, 'title' => 'Resource Requests Report',
        ], $totalsRows);
    }

    // ─── 6. CENTER ISSUES ───

    #[OA\Get(
        path: '/analytics/export/issues',
        summary: 'Export Center Issues Summary',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'format', in: 'query', description: 'Export format (csv, pdf)', required: false, schema: new OA\Schema(type: 'string', enum: ['csv', 'pdf'], default: 'csv'))]
    #[OA\Response(response: 200, description: 'Success')]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function centerIssues(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');
        $meta = $this->getFilterMeta($request);

        $query = CenterIssueReport::with(['center', 'reporter', 'handler', 'category', 'severityLevel', 'status']);

        $user = Auth::user();
        if ($user->isEvacPersonnel() && $user->assigned_center_id) {
            $query->where('evacuation_center_id', $user->assigned_center_id);
        } elseif ($request->filled('center_id') && $request->center_id !== 'all') {
            $query->where('evacuation_center_id', $request->center_id);
        }
        if ($request->filled('start_date')) $query->whereDate('created_at', '>=', $request->start_date);
        if ($request->filled('end_date')) $query->whereDate('created_at', '<=', $request->end_date);

        $items = $query->latest()->get();

        $headers = [
            'Report ID','Evacuation Center','Category','Title','Description',
            'Severity','Status','Reported By','Handled By','Date Reported','Date Updated',
        ];

        $rows = [];
        foreach ($items as $item) {
            $rows[] = [
                $item->report_id,
                $item->center?->name ?? '',
                $item->category?->category_label ?? '',
                $item->title ?? '',
                $item->description ?? '',
                $item->severityLevel?->severity_label ?? '',
                $item->status?->status_label ?? '',
                $item->reporter?->name ?? '',
                $item->handler?->name ?? '',
                $item->created_at?->format('Y-m-d H:i') ?? '',
                $item->updated_at?->format('Y-m-d H:i') ?? '',
            ];
        }

        $totalsRows = [
            ['Total Reports',   count($rows)],
            ['Open',            count(array_filter($rows, fn($r) => stripos($r[6] ?? '', 'open') !== false))],
            ['Resolved',        count(array_filter($rows, fn($r) => stripos($r[6] ?? '', 'resolved') !== false))],
        ];

        return $this->respond($request, $headers, $rows, 'Center_Issues', 'exports.table-report', [
            'meta' => $meta, 'headers' => $headers, 'rows' => $rows, 'title' => 'Center Issue Reports',
        ], $totalsRows);
    }

    // ─── 7. DAILY INTAKE TRENDS (CSV only) ───

    #[OA\Get(
        path: '/analytics/export/daily-intake',
        summary: 'Export Daily Intake Trends (CSV only)',
        security: [['bearerAuth' => []]],
        tags: ['Analytics']
    )]
    #[OA\Parameter(name: 'event_id', in: 'query', description: 'Filter by event ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'center_id', in: 'query', description: 'Filter by center ID', required: false, schema: new OA\Schema(type: 'string'))]
    #[OA\Parameter(name: 'start_date', in: 'query', description: 'Start date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Parameter(name: 'end_date', in: 'query', description: 'End date filter', required: false, schema: new OA\Schema(type: 'string', format: 'date'))]
    #[OA\Response(
        response: 200, 
        description: 'CSV file download response',
        content: new OA\MediaType(
            mediaType: 'text/csv'
        )
    )]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    public function dailyIntake(Request $request)
    {
        $this->authorizeRole('super_admin', 'evac_admin', 'evac_personnel');

        $query = EvacuationRecord::with('center');
        $this->applyFilters($request, $query);

        $records = $query->orderBy('created_at')->get();

        $headers = ['Date','Evacuation Center','New Households','New Individuals'];
        $rows = [];

        $grouped = $records->groupBy(function ($r) {
            return $r->created_at->format('Y-m-d') . '|' . $r->center_id;
        });

        foreach ($grouped as $key => $group) {
            [$date] = explode('|', $key);
            $rows[] = [
                $date,
                $group->first()->center?->name ?? '',
                $group->pluck('household_id')->unique()->count(),
                (int) $group->sum('evacuated_count'),
            ];
        }

        $totalHouseholds = (int) array_sum(array_column($rows, 2));
        $totalIndividuals = (int) array_sum(array_column($rows, 3));

        $totalsRows = [
            ['Total New Households (period)',   $totalHouseholds],
            ['Total New Individuals (period)',  $totalIndividuals],
        ];

        $meta = $this->getFilterMeta($request);
        $meta['title'] = 'Daily Intake Trends';

        $fileName = 'Daily_Intake_' . now()->format('Y-m-d') . '.csv';
        return $this->streamCsv($fileName, $headers, $rows, $meta, $totalsRows);
    }
}

