<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'EvaTrack Report' }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 11px;
            color: #334155;
            margin: 0;
            padding: 0;
            line-height: 1.4;
        }
        .header {
            margin-bottom: 20px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
        }
        .brand {
            font-size: 18px;
            font-weight: bold;
            color: #1e293b;
            text-transform: uppercase;
        }
        .brand-blue {
            color: #2563eb;
        }
        .report-title {
            font-size: 16px;
            font-weight: bold;
            color: #0f172a;
            margin-top: 5px;
        }
        .meta-table {
            width: 100%;
            margin-top: 10px;
            font-size: 10px;
            color: #64748b;
        }
        .meta-table td {
            padding: 2px 0;
        }
        .meta-label {
            font-weight: bold;
            color: #475569;
            width: 12%;
        }
        .meta-value {
            width: 38%;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 9px;
        }
        table.data-table th {
            background-color: #f1f5f9;
            color: #475569;
            font-weight: bold;
            text-align: left;
            padding: 6px 8px;
            border: 1px solid #cbd5e1;
            text-transform: uppercase;
            font-size: 8px;
        }
        table.data-table td {
            padding: 6px 8px;
            border: 1px solid #e2e8f0;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            position: fixed;
            bottom: -30px;
            left: 0;
            right: 0;
            height: 30px;
            font-size: 8px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 5px;
            text-align: center;
        }
        .text-center {
            text-align: center;
        }
        .text-right {
            text-align: right;
        }
        .font-bold {
            font-weight: bold;
        }
        .badge {
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 8px;
            font-weight: bold;
        }
        .badge-optimal {
            background-color: #dcfce7;
            color: #15803d;
        }
        .badge-warning {
            background-color: #fef9c3;
            color: #a16207;
        }
        .badge-critical {
            background-color: #fee2e2;
            color: #b91c1c;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <table style="width: 100%;">
            <tr>
                <td>
                    <span class="brand">EVA<span class="brand-blue">TRACK</span></span>
                    <div style="font-size: 8px; color: #64748b; letter-spacing: 1px;">PRECISION SAFETY & EVACUATION MANAGEMENT</div>
                </td>
                <td class="text-right" style="vertical-align: bottom; font-size: 9px; color: #64748b;">
                    Generated: {{ $meta['generated_at'] }}
                </td>
            </tr>
        </table>
        <div class="report-title">{{ $title }}</div>
        
        <table class="meta-table">
            <tr>
                <td class="meta-label">Disaster Event:</td>
                <td class="meta-value">{{ $meta['event'] }}</td>
                <td class="meta-label">Date Filter:</td>
                <td class="meta-value">
                    @if($meta['start_date'] !== 'N/A' || $meta['end_date'] !== 'N/A')
                        {{ $meta['start_date'] }} to {{ $meta['end_date'] }}
                    @else
                        All Dates
                    @endif
                </td>
            </tr>
            <tr>
                <td class="meta-label">Center Context:</td>
                <td class="meta-value">{{ $meta['center'] }}</td>
                <td class="meta-label">Generated By:</td>
                <td class="meta-value">{{ $meta['generated_by'] }}</td>
            </tr>
        </table>
    </div>

    @yield('content')

    <div class="footer">
        <table style="width: 100%;">
            <tr>
                <td>EvaTrack Emergency Response Platform &copy; {{ date('Y') }}</td>
                <td class="text-right">Confidential - For Official DRRM Use Only</td>
            </tr>
        </table>
    </div>
</body>
</html>
