<?php

namespace App\Domains\EvacuationCenters\Controllers;

use App\Http\Controllers\Controller;
use App\Domains\EvacuationCenters\Models\EvacuationCenter;
use App\Domains\Evacuations\Models\EvacuationRecord;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Carbon\Carbon;
use OpenApi\Attributes as OA;

class CenterExportController extends Controller
{
    #[OA\Get(path: '/evacuation-centers/{center}/export', summary: 'Export evacuated household data for a given center as CSV', security: [['bearerAuth' => []]], tags: ['Evacuation Centers'])]
    #[OA\Parameter(name: 'center', in: 'path', description: 'Center ID', required: true, schema: new OA\Schema(type: 'integer'))]
    #[OA\Parameter(name: 'type', in: 'query', description: 'Export granularity type', required: false, schema: new OA\Schema(type: 'string', enum: ['household', 'member'], default: 'member'))]
    #[OA\Response(response: 200, description: 'CSV file download response', content: new OA\MediaType(mediaType: 'text/csv'))]
    #[OA\Response(response: 401, description: 'Unauthenticated')]
    #[OA\Response(response: 403, description: 'Forbidden')]
    #[OA\Response(response: 404, description: 'Center not found')]
    public function exportCenterHouseholds(Request $request, $centerId)
    {
        $user = Auth::user();
        if ($user->isEvacPersonnel()) {
            if (!$user->assigned_center_id || $user->assigned_center_id !== $centerId) {
                return response()->json(['message' => 'Unauthorized'], 403);
            }
        } elseif (!$user->isSuperAdmin() && !$user->isEvacAdmin()) {
            return response()->json(['message' => 'Unauthorized'], 403);
        }

        $center = EvacuationCenter::where('evacuation_center_id', $centerId)->firstOrFail();
        $exportType = $request->input('type', 'member');

        $records = EvacuationRecord::with([
            'household.address.barangay.city.province',
            'household.address.purok',
            'household.address.sitio',
            'household.address.zipcode',
            'household.members.gender',
            'household.members.civilStatus',
            'household.members.relationship',
            'household.members.vulnerableGroupDetails',
            'evacuatedMembers',
            'unitAllocations.unit.type',
            'event',
            'verifier',
        ])
            ->where('center_id', $centerId)
            ->where('household_status_id', 2)
            ->latest('verified_at')
            ->get();

        $fileName = $this->sanitizeFileName($center->name) . '_Evacuees_' . now()->format('Y-m-d') . '.csv';

        if ($exportType === 'household') {
            return $this->streamHouseholdCsv($records, $fileName, $center);
        }
        return $this->streamMemberCsv($records, $fileName, $center);
    }

    // ── Meta block ──────────────────────────────────────────────────────────────

    private function writeMetaBlock($handle, EvacuationCenter $center, string $exportType): void
    {
        $user = Auth::user();
        $typeLabel = $exportType === 'household'
            ? 'Household Summary  (1 row per household)'
            : 'Individual Member List  (1 row per evacuated member)';

        fputcsv($handle, ['EvaTrack Emergency Response Platform — Evacuation Record Export']);
        fputcsv($handle, []);
        fputcsv($handle, ['Report Type',       $typeLabel]);
        fputcsv($handle, ['Evacuation Center', $center->name]);
        fputcsv($handle, ['Center Address',    $center->osm_address ?? 'N/A']);
        fputcsv($handle, ['Generated By',      $user?->name ?? 'System']);
        fputcsv($handle, ['Generated At',      now()->format('F j, Y  H:i:s')]);
        fputcsv($handle, []);
        fputcsv($handle, ['NOTE: For official DRRM use only. Do not redistribute without authorization.']);
        fputcsv($handle, []);
        fputcsv($handle, ['--- DATA STARTS BELOW ---']);
        fputcsv($handle, []);
    }

    // ── Household-level export ───────────────────────────────────────────────────

    private function streamHouseholdCsv($records, $fileName, EvacuationCenter $center): StreamedResponse
    {
        return $this->streamCsv($fileName, function ($handle) use ($records, $center) {
            $this->writeMetaBlock($handle, $center, 'household');

            fputcsv($handle, [
                'No.', 'Household ID', 'Family / Household Name', 'Contact Number', 'Emergency Contact',
                'Home Address (Purok/Sitio)', 'Barangay', 'City / Municipality',
                'Disaster Event', 'Evacuation Status', 'Total Evacuated Members',
                'Checkout Status', 'Date & Time Checked Out',
                'Allocated Unit / Room', 'Unit Type',
                'Admission Method', 'Verified / Admitted By', 'Date & Time Admitted',
                'Evacuation Center', 'Export Date',
            ]);

            $no = 1; $totalHouseholds = 0; $totalEvacuated = 0;

            foreach ($records as $record) {
                $hh             = $record->household;
                $unitAllocation = $record->unitAllocations->first();
                $evacuatedCount = (int) ($record->evacuated_count ?? 0);
                $totalEvacuated += $evacuatedCount;
                $totalHouseholds++;

                $checkoutAt   = $record->checkout_at ? Carbon::parse($record->checkout_at)->format('Y-m-d H:i') : null;
                $addr         = $hh?->address;
                $purokSitio   = trim(($addr?->purok?->purok_name ?? '') . ' ' . ($addr?->sitio?->sitio_name ?? '')) ?: ($addr?->street_address ?? '');
                $barangay     = $addr?->barangay?->barangay_name ?? '';
                $city         = $addr?->barangay?->city?->city_name ?? '';

                fputcsv($handle, [
                    $no++,
                    $record->household_id,
                    $hh?->household_name ?? '',
                    $hh?->contact_number ?? '',
                    $hh?->emergency_contact ?? '',
                    $purokSitio, $barangay, $city,
                    $record->event?->name ?? '',
                    'Evacuated',
                    $evacuatedCount,
                    $checkoutAt ? 'Checked Out' : 'Active (Still Evacuated)',
                    $checkoutAt ?? '',
                    $unitAllocation?->unit?->name ?? 'Unassigned',
                    $unitAllocation?->unit?->type?->type_label ?? '',
                    ucfirst($record->method ?? 'manual'),
                    $record->verifier?->name ?? '',
                    $record->verified_at ? Carbon::parse($record->verified_at)->format('Y-m-d H:i') : '',
                    $center->name,
                    now()->format('Y-m-d'),
                ]);
            }

            fputcsv($handle, []);
            fputcsv($handle, [
                'TOTALS', '', $totalHouseholds . ' Household(s)', '', '', '', '', '',
                '', '', $totalEvacuated . ' Individual(s)', '', '', '', '', '', '', '',
                $center->name, '',
            ]);
            fputcsv($handle, []);
            fputcsv($handle, ['Generated by EvaTrack — ' . now()->format('F j, Y H:i')]);
        });
    }

    // ── Member-level export ──────────────────────────────────────────────────────

    private function streamMemberCsv($records, $fileName, EvacuationCenter $center): StreamedResponse
    {
        return $this->streamCsv($fileName, function ($handle) use ($records, $center) {
            $this->writeMetaBlock($handle, $center, 'member');

            fputcsv($handle, [
                // Row
                'No.',
                // Household identification
                'Household ID', 'Family / Household Name', 'Household Contact', 'Household Emergency Contact',
                // Location
                'Purok / Sitio', 'Barangay', 'City / Municipality',
                // Member identity
                'Member ID', 'Last Name', 'First Name', 'Middle Name',
                // Demographics
                'Date of Birth', 'Age', 'Age Group', 'Sex / Gender', 'Civil Status', 'Relationship to Household Head',
                // Vulnerability flags (Yes/No — filterable in Excel)
                'PWD', 'Pregnant', 'Senior Citizen (60+)', 'Indigenous People (IP)', 'Other Vulnerable Groups',
                // Status
                'Member Evacuation Status', 'Household Checkout Status', 'Date & Time Checked Out',
                // Accommodation
                'Allocated Unit / Room', 'Unit Type',
                // Audit trail
                'Disaster Event', 'Admission Method', 'Verified / Admitted By', 'Date & Time Admitted',
                // Export
                'Evacuation Center', 'Export Date',
            ]);

            $no = 1;
            $totalMembers = $totalEvacuated = $totalPwd = $totalPregnant = 0;
            $totalSenior = $totalIndigenous = $totalMale = $totalFemale = 0;
            $ageCounts = ['infant' => 0, 'child1' => 0, 'child2' => 0, 'youth' => 0, 'adult' => 0, 'senior' => 0];

            foreach ($records as $record) {
                $hh                 = $record->household;
                $unitAllocation     = $record->unitAllocations->first();
                $evacuatedMemberIds = $record->evacuatedMembers->pluck('member_id')->toArray();
                $members            = $hh?->members ?? collect();

                $checkoutAt     = $record->checkout_at ? Carbon::parse($record->checkout_at)->format('Y-m-d H:i') : null;
                $checkoutStatus = $checkoutAt ? 'Checked Out' : 'Active (Still Evacuated)';

                $addr       = $hh?->address;
                $purokSitio = trim(($addr?->purok?->purok_name ?? '') . ' ' . ($addr?->sitio?->sitio_name ?? '')) ?: ($addr?->street_address ?? '');
                $barangay   = $addr?->barangay?->barangay_name ?? '';
                $city       = $addr?->barangay?->city?->city_name ?? '';

                if ($members->isEmpty()) {
                    fputcsv($handle, [
                        $no++, $record->household_id, $hh?->household_name ?? '',
                        $hh?->contact_number ?? '', $hh?->emergency_contact ?? '',
                        $purokSitio, $barangay, $city,
                        '', '', '', '', '', '', '', '', '', '',
                        '', '', '', '', '',
                        'No Members Recorded', $checkoutStatus, $checkoutAt ?? '',
                        $unitAllocation?->unit?->name ?? 'Unassigned',
                        $unitAllocation?->unit?->type?->type_label ?? '',
                        $record->event?->name ?? '', ucfirst($record->method ?? 'manual'),
                        $record->verifier?->name ?? '',
                        $record->verified_at ? Carbon::parse($record->verified_at)->format('Y-m-d H:i') : '',
                        $center->name, now()->format('Y-m-d'),
                    ]);
                    continue;
                }

                foreach ($members as $member) {
                    $age         = $member->birth_date ? Carbon::parse($member->birth_date)->age : null;
                    $ageGroup    = $this->getAgeGroup($age);
                    $isEvacuated = in_array($member->member_id, $evacuatedMemberIds);

                    $vgKeys   = $member->vulnerableGroupDetails->pluck('vulnerable_group_key')->toArray();
                    $vgLabels = $member->vulnerableGroupDetails->pluck('vulnerable_group_label')->toArray();

                    $isPwd        = in_array('pwd', $vgKeys);
                    $isPregnant   = in_array('pregnant', $vgKeys);
                    $isSenior     = in_array('elderly', $vgKeys) || ($age !== null && $age >= 60);
                    $isIndigenous = in_array('indigenous', $vgKeys);
                    $otherLabels  = array_values(array_filter($vgLabels, fn($l) =>
                        !in_array(strtolower($l), ['pwd', 'pregnant', 'elderly', 'senior citizen', 'indigenous', 'indigenous people'])
                    ));

                    $genderLabel = $member->gender?->gender_label ?? '';
                    $genderKey   = strtolower($member->gender?->gender_key ?? '');

                    if ($isEvacuated) {
                        $totalEvacuated++;
                        if ($isPwd)        $totalPwd++;
                        if ($isPregnant)   $totalPregnant++;
                        if ($isSenior)     $totalSenior++;
                        if ($isIndigenous) $totalIndigenous++;
                        if ($genderKey === 'male')   $totalMale++;
                        if ($genderKey === 'female') $totalFemale++;
                        if ($age !== null) {
                            if ($age < 1)       $ageCounts['infant']++;
                            elseif ($age <= 5)  $ageCounts['child1']++;
                            elseif ($age <= 11) $ageCounts['child2']++;
                            elseif ($age <= 17) $ageCounts['youth']++;
                            elseif ($age <= 59) $ageCounts['adult']++;
                            else                $ageCounts['senior']++;
                        }
                    }
                    $totalMembers++;

                    fputcsv($handle, [
                        $no++,
                        $record->household_id, $hh->household_name ?? '',
                        $hh->contact_number ?? '', $hh->emergency_contact ?? '',
                        $purokSitio, $barangay, $city,
                        $member->member_id,
                        $member->last_name ?? '', $member->first_name ?? '', $member->middle_name ?? '',
                        $member->birth_date ? Carbon::parse($member->birth_date)->format('Y-m-d') : '',
                        $age ?? '', $ageGroup, $genderLabel,
                        $member->civilStatus?->status_label ?? '',
                        $member->relationship?->relationship_label ?? '',
                        $isPwd        ? 'Yes' : 'No',
                        $isPregnant   ? 'Yes' : 'No',
                        $isSenior     ? 'Yes' : 'No',
                        $isIndigenous ? 'Yes' : 'No',
                        implode('; ', $otherLabels) ?: '',
                        $isEvacuated ? 'Evacuated' : 'Not Evacuated',
                        $checkoutStatus, $checkoutAt ?? '',
                        $unitAllocation?->unit?->name ?? 'Unassigned',
                        $unitAllocation?->unit?->type?->type_label ?? '',
                        $record->event?->name ?? '', ucfirst($record->method ?? 'manual'),
                        $record->verifier?->name ?? '',
                        $record->verified_at ? Carbon::parse($record->verified_at)->format('Y-m-d H:i') : '',
                        $center->name, now()->format('Y-m-d'),
                    ]);
                }
            }

            fputcsv($handle, []);
            fputcsv($handle, ['--- SUMMARY TOTALS ---']);
            fputcsv($handle, ['Total Member Rows',        $totalMembers]);
            fputcsv($handle, ['Total Evacuated Members',  $totalEvacuated]);
            fputcsv($handle, ['Male',                     $totalMale]);
            fputcsv($handle, ['Female',                   $totalFemale]);
            fputcsv($handle, ['Infants (< 1 yr)',          $ageCounts['infant']]);
            fputcsv($handle, ['Children (1-5)',            $ageCounts['child1']]);
            fputcsv($handle, ['Children (6-11)',           $ageCounts['child2']]);
            fputcsv($handle, ['Youth (12-17)',             $ageCounts['youth']]);
            fputcsv($handle, ['Adults (18-59)',            $ageCounts['adult']]);
            fputcsv($handle, ['Senior Citizens (60+)',     $ageCounts['senior']]);
            fputcsv($handle, ['PWD',                      $totalPwd]);
            fputcsv($handle, ['Pregnant',                 $totalPregnant]);
            fputcsv($handle, ['Senior Citizens (Flag)',   $totalSenior]);
            fputcsv($handle, ['Indigenous People (IP)',   $totalIndigenous]);
            fputcsv($handle, []);
            fputcsv($handle, ['Generated by EvaTrack Emergency Response Platform — ' . now()->format('F j, Y H:i')]);
        });
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────

    private function getAgeGroup(?int $age): string
    {
        if ($age === null) return '';
        if ($age < 1)   return 'Infant (< 1 yr)';
        if ($age <= 5)  return 'Child (1-5)';
        if ($age <= 11) return 'Child (6-11)';
        if ($age <= 17) return 'Youth (12-17)';
        if ($age <= 59) return 'Adult (18-59)';
        return 'Senior Citizen (60+)';
    }

    private function streamCsv(string $fileName, callable $writeRows): StreamedResponse
    {
        return new StreamedResponse(function () use ($writeRows) {
            $handle = fopen('php://output', 'w');
            fprintf($handle, chr(0xEF) . chr(0xBB) . chr(0xBF)); // UTF-8 BOM
            $writeRows($handle);
            fclose($handle);
        }, 200, [
            'Content-Type'        => 'text/csv; charset=UTF-8',
            'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
            'Cache-Control'       => 'no-cache, no-store, must-revalidate',
            'Pragma'              => 'no-cache',
            'Expires'             => '0',
        ]);
    }

    private function sanitizeFileName(string $name): string
    {
        return preg_replace('/[^A-Za-z0-9_\-]/', '_', str_replace(' ', '_', $name));
    }
}
